[project]
name = "weather-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "requests>=2.32.5",
    "fastapi>=0.110.0",
    "pydantic>=2.0.0",
    "httpx>=0.27.0",
    "uvicorn>=0.29.0",
]
